### ISSUE TITLE
Contributor Guidelines

### ISSUE THREAD

**Issue by neslihanatasever** [gulcin/tech-conference-organizer#2]
Hi, the Contributor Guidelines link under the Contributing heading is not working.
If you want, I can help you fill in this link. If it's not an error, just point it out. 
![Ekran görüntüsü 2024-07-18 022646](https://github.com/user-attachments/assets/d7c8874e-5b69-41eb-a074-a06efe897198)

**Comment by gulcin** [comment]
Feel free to fix it, thanks Neslihan!

**Comment by gulcin** [comment]
Fixed by @neslihanatasever with #4 🎉
